export default function Head() {
  return (
    <>
      <title>pdsbox's blog</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      {/* <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/xeicon@2.3.3/xeicon.min.css" /> */}
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}
